version: '3'

networks:
  popcorn:

volumes:
  mariadb_data:

services:
  mariadb:
    container_name: popcorn_mariadb
    image: mariadb:10.3
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 127.0.0.1:3309:3306
    networks:
      - popcorn
    environment:
      MYSQL_ROOT_PASSWORD: root_pasword
      MYSQL_USER: popcorn
      MYSQL_PASSWORD: popcorntime
      MYSQL_DATABASE: popcorn_time
  phpmyadmin:
    container_name: popcorn_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1:8180:80
    networks:
      - popcorn
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      PMA_PORT: 3306
      PMA_HOST: mariadb